
#capital_cities=["nairobi","joburg","beijing","cairo","moscow","kampala","dar"]
#print(capital_cities[6]) 

#replacing items
#fruits=["apples","oranges","bananas","mangoes"]
#fruits[2]="watermelon"
#print(fruits) 

#adding new items
#fruit=["mangoes","orange","apples"] 
#fruit.append("banana",)
#fruit.append("strawberry")
#print(fruit)         

#removing items
#counties=["nairobi","kiambu","laikipia","machakos"]
#ounties.remove("laikipia")
#counties.remove("kiambu")
#print(counties)

counties=["nairobi","kiambu","laikipia","machakos"]
counties.pop()
print(counties)