import tkinter as tk
root=tk.Tk()
root.title('Tkinter Place Geometry Manager')
root.geometry("600x400")
label_dig=tk.Label(master=root,text="Digital",bg='white',font=("Roboto",12,"bold"),fg='#3751FE')
label_dig.place(x=50,y=20)
label_art=tk.Label(master=root,text="Artificial Intelligence Driving\nResults For The Travel Industry",bg='white',font=("Open Sans",12,"bold"),fg='#3751FE',justify="left")
label_art.place(x=50,y=50)
label_wel=tk.Label(master=root,text="Welcome  back! Please login to your account.",bg='white',font=("Roboto",12),fg='#000000')
label_wel.place(x=50,y=120)
label_mail=tk.Label(master=root,text="Email Address",bg='white',fg='#000000')
label_mail.place(x=50,y=180)
entry_mail=tk.Entry(root,font=("arial",12),fg='#000000',width=30)
entry_mail.place(x=50,y=200)
label_pass=tk.Label(master=root,text="Password",bg='white',fg='#000000')
label_pass.place(x=50,y=250)
entry_pass=tk.Entry(root,font=("arial",12),fg='#000000',width=30)
entry_pass.place(x=50,y=270)
# label_rem=tk.Label(master=root,text="Remember Me",bg='white',font=("Roboto",12),fg='#000000')
# label_rem.place(x=50,y=115)
# label_for=tk.Label(master=root,text="Forgot Password",bg='white',font=("Roboto",12),fg='#000000')
# label_for.place(x=50,y=155)
label_log=tk.Button(text="Login",bg='#3751FE',fg="white")
label_log.place(x=50,y=370)
label_sign=tk.Button(text="Sign Up",bg="white",fg='#0C31F1')
label_sign.place(x=200,y=370)
root.mainloop()
    


